---
title: "HW10"
author: "Alex Parra"
date: "5/5/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
```


# Problem 1


```{r}
y <- c(1, 0, 0, 1, 2, 3, 3)
x1 <- c(-3, -2, -1, 0, 1, 2, 3)
x2 <- c(5, 0, -3, -4, -3, 0, 5)
x3 <- c(-1, 1, 1, 0, -1, -1, 1)
df <- data.frame(y, x1, x2, x3)
df
```

## Part (a)

```{r}
m1 <- lm(y ~ x1 + x2 + x3, data = df)
summary(m1)
```

We get this equation:

\[
  \hat{y} = 1.42857 + 0.50000 \times x_1 + 0.11905 \times x_2 -0.50000 \times x_3
\]

```{r reg-with-line}
ggplot(data = df, aes(x = x1, y = y)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE)
ggplot(data = df, aes(x = x2, y = y)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE)
ggplot(data = df, aes(x = x3, y = y)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE)
```

## Part (b)

```{r}
x_1=1
x_2=-3
x_3=-1
y_hat = 1.42857 + 0.50000 * x_1 + 0.11905 * x_2 -0.50000 * x_3
y_hat
```



## Part (c)

```{r}

X = matrix(c(c(1,1,1,1,1,1,1),x1,x2,x3), ncol=4, nrow=7)
Y = matrix(y, ncol=1, nrow=7)
B = matrix(c(1.42857, 0.50000, 0.11905, -0.50000), ncol=1, nrow=4)

SSE=(t(Y)%*%Y)-t(X%*%B)%*%Y
print("SSE: ")
SSE
sigma_sq=SSE/(7-3-1)
print("sigma_sq: ")
sigma_sq
sigma=sqrt(sigma_sq)
print("sigma: ")
sigma
```

```{r}
a=matrix(c(1,1,-3,-1), ncol=1, nrow=4)
x=matrix(c(1,-3,-1), ncol=1, nrow=3)
t_alpha=3.182

fix=(t(a)%*%B)
range=t_alpha*sigma*sqrt(1+t(a)%*%solve(t(X)%*%X)%*%a)
fix
range
PI=c(fix-range, fix+range)
print("PI: ")
PI
```

